version: "3.3"

services:
  nginx:
    image: nginx
    ports:
      - "8001:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/ssl:/etc/ssl:ro
      - ./dist:/usr/share/nginx/html:ro